### ISSUE TITLE
GKE Ingress

### ISSUE THREAD

**Issue by keewooi** [CovidShield/server#87]
Hi,

I intend to deploy this into a GKE cluster and would like to use its Ingress instead of Nginx. One of the GKE ingress requirements is to have all services return a 200 at '/' or a `readinessProbe` on a path that returns a 200 ([1]), otherwise the backend will be seen as unhealthy.

For key-submission, I can set up a `readinessProbe` like the following:

```
readinessProbe:
  httpGet:
    path: /exposure-configuration/ON.json
    port: 8001
```

I can't find out a way to do for key-retrieval though.

Can you please advise if there is a recommended way to make the server work with GKE Ingress? Thanks.

[1]: https://github.com/kubernetes/kubernetes/issues/20555
